#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# en el if:  4 >= num de argumentos
# scp opcion -i para indicar de que file toma la key privada
if [ "$#" -ge 4 ]
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
