#!/usr/bin/env bash
# Install nginx web server
sudo apt update
sudo apt-get -y install nginx
cd /var/www/html
sudo chmod 666 index.nginx-debian.html
echo "Hello World!" > index.nginx-debian.html
sudo service nginx restart
