#!/usr/bin/env bash
# Install nginx web server
sudo apt update
sudo apt-get -y install nginx
cd /var/www/html
sudo chmod 666 index.nginx-debian.html
echo "Hello World!" > index.nginx-debian.html
new="https://www.youtube.com/watch?v=QH2-TGUlwu4&ab_channel=NyanCat"
sed -i "s/server_name/return 301 $new_string;/" file
sudo service nginx restart
