#!/usr/bin/env bash
# Install nginx web server
sudo apt update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo touch /var/www/html/error.html
sudo chmod 777 /var/www/html/error.html
sudo echo "Ceci n'est pas une page" > /var/www/html/error.html
# coloca en la linea 70 la pagina de error"
sudo sed -i '70i error_page 404 ./error.html;' /etc/nginx/sites-enabled/default
sudo service nginx restart
