#!/usr/bin/env bash
# Install nginx web server
sudo apt update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" > /var/www/html/error.html
sudo sed -i '/server_name _;/a error_page 404 /error.html;\nlocation = /error.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
