#!/usr/bin/env bash
# configure Nginx HEAD

sudo apt update
sudp apt-get -y install nginx
sudo sed -i "/listen 80 default_server/a add_header X-Served-By: '$HOSTNAME';" /etc/nginx/sites-enabled/default
sudo service ngnix restart
