#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# tee -a -> append texto en una archivo
# instalo haproxy
# coloco listen y el server del load balancer
# le paso puerto
# le paso tipo de algoritmo (roundrobin)
# le paso los servers a loadbalancear
# los agrego al file /etc/haproxy/haproxy.cfg

sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install haproxy
echo  "
listen 4423-lb-01
	bind *:80
	balance roundrobin 
	server 4423-web-01 54.221.17.30:80 check 
    	server 4423-web-02 54.172.183.211:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
