#!/usr/bin/env bash
# Run Nginx as Nginx

sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
lsof -i:8080
sudo -u nginx service nginx restart
